spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juancarloscoripoma/config-ssh-dev.git
          force-pull: true
    #config rabbitmq and bus refresh properties add
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1 #config ip rabbitmq
                port: 5672
                username: admin
                password: admin
#config port
server:
  port: 8888
#context config
management:
  context-path: /admin
  security:
    enabled: false
#discovery OFF config
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
